# These are supported funding model platforms

github: paulovicks
patreon: Paulovicks
buy_me_a_coffee: paulovicks
custom: [Ethereum - 0xe4eE9f0CBC636682Cb97EdCb143b9EAE7C13bB3D, Filecoin - f1glg4lzjeizqs7nxuahe6liomjhensmtih4g4oyq, Solana - 3H1PETmAbTdDHxe33qf5ykqPdkNnJSBmQ8ZxF2yaL3pc]
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
